### PR TITLE
feat: buttons for selecting type on TheAddItemView.vue

### PR DESCRIPTION
**Pull request by banneux-florent**
Added 4 colored buttons that match previous item types color. No type selected at first, all are is-outlined.

### CODE REVIEW

**Comment by banneux-florent** [comment]
Sorry for ping urubens! Default reviewer, didn't check.. :stuck_out_tongue:

**Comment by rmaree** [comment]
Seems it will also close issue #38, right ?

**Comment by banneux-florent** [comment]
We made a duplicate of that issue apparently yes!

**Review by rmaree — CHANGES_REQUESTED** [review]
I believe we should keep the "Type ?" (with the tooltip), it seems to be lost in your code.
Maybe visually this could be on a new line (rather than on the same line than name) to avoid a user missing it.

**Comment by banneux-florent** [comment]
> I believe we should keep the "Type ?" (with the tooltip), it seems to be lost in your code. Not sure but maybe in addition visually this could be on a new line (rather than on the same line than name) to avoid a user missing the selection of the type ?

My fault yes, it's definitely better with it. Label and tooltip added back. I committed as usual, hope it should be done like that in the pull request process?

**Review by rmaree — APPROVED** [review]

**Comment by rmaree** [comment]
Thanks ! closes #57 closes #38

**Pull request merged**
